session_name: Zea Svelte Template
suppress_history: false
windows:
  - layout: main-vertical
    panes:
      - yarn run dev
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
